'use strict';
console.log('hello, world');
const $h1 = document.querySelector('h1');
console.log($h1);
console.dir($h1);
const $id = document.querySelector('#explanation');
console.log($id);
console.dir($id);
const $class = document.querySelector('.hint');
console.log($class);
console.dir($class);
const $nodes = document.querySelectorAll('p');
console.log($nodes);
const $nodeslink = document.querySelectorAll('.example-link');
console.log($nodeslink);
