'use strict';
const fullName = 'Kyle Spence';
const isCool = true;
const totalPets = 1;
console.log('full name:', fullName);
console.log('is cool?:', isCool);
console.log('pets?', totalPets);
console.log('typeof full name:', typeof fullName);
console.log('typeof is cool:', typeof isCool);
console.log('typeof total pets:', typeof totalPets);
const empty = null;
console.log('empty:', empty);
console.log('typeof empty:', typeof empty);
const nothing = undefined;
console.log('nothing:', nothing);
console.log('typeof nothing:', typeof nothing);
