'use strict';
const width = 5;
const height = 3;
const area = width * height;
console.log('area:', area);
console.log('typeof area:', typeof area);
const bill = 5;
const payment = 10;
const change = payment - bill;
console.log('change:', change);
console.log('typeof change:', typeof change);
const quizzes = 4;
const midterm = 1;
const final = 1;
const grade = (quizzes + midterm + final) / 3;
console.log('grade:', grade);
console.log('type of grade:', typeof grade);
const firstName = 'Kyle';
const lastName = 'Spence';
const fullName = firstName + ' ' + lastName;
console.log('My name is ', fullName);
console.log('Type of fullName:', typeof fullName);
const pH = 14;
const isAcidic = pH < 7;
console.log('Acidic?', isAcidic);
console.log('type of isAcidic:', typeof isAcidic);
const headCount = 301;
const isSparta = headCount === 300;
console.log('Same as sparta?', isSparta);
console.log('type of isSparta', typeof isSparta);
let motto = fullName;
motto += ' is the goat!';
console.log('Favorite saying:', motto);
console.log('type of motto:', typeof motto);
